# Generated by Django 5.1 on 2024-09-01 22:12

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/', validators=[tasks.models.validate_image_size]),
        ),
    ]
