# Generated by Django 5.1 on 2024-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Normal', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Todo', max_length=255),
        ),
    ]
